In [7]:
# Load the Pandas libraries with alias 'pd' 
import pandas as pd 
# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
data = pd.read_csv('./covid19.csv') 
# Preview the first 5 lines of the loaded data 
data.head()

,dateRep,day,month,year,cases,deaths,geoId,continentExp,countryterritoryCode,popData2018,countriesAndTerritories
0,20/04/2020,20,4,2020,88,3,AF,Asia,AFG,37172386.0,Afghanistan
1,19/04/2020,19,4,2020,63,0,AF,Asia,AFG,37172386.0,Afghanistan
2,18/04/2020,18,4,2020,51,1,AF,Asia,AFG,37172386.0,Afghanistan
3,17/04/2020,17,4,2020,10,4,AF,Asia,AFG,37172386.0,Afghanistan
4,16/04/2020,16,4,2020,70,2,AF,Asia,AFG,37172386.0,Afghanistan

In [13]:
today_data = data.loc[data['dateRep'] == "20/04/2020"]
print(today_data)

          dateRep  day  month  year  cases  deaths geoId continentExp  \
0      20/04/2020   20      4  2020     88       3    AF         Asia
102    20/04/2020   20      4  2020     14       0    AL       Europe
145    20/04/2020   20      4  2020     94       8    DZ       Africa
252    20/04/2020   20      4  2020      9       1    AD       Europe
290    20/04/2020   20      4  2020      0       0    AO       Africa
320    20/04/2020   20      4  2020      0       0    AI      America
345    20/04/2020   20      4  2020      0       0    AG      America
377    20/04/2020   20      4  2020    102       2    AR      America
422    20/04/2020   20      4  2020     48       2    AM       Europe
525    20/04/2020   20      4  2020      1       0    AW      America
554    20/04/2020   20      4  2020     26       1    AU      Oceania
666    20/04/2020   20      4  2020     48       9    AT       Europe
778    20/04/2020   20      4  2020     25       1    AZ       Europe
883    20/04/2020   20      4  2020      2       0    BS      America
917    20/04/2020   20      4  2020    100       0    BH         Asia
1028   20/04/2020   20      4  2020    312       7    BD         Asia
1065   20/04/2020   20      4  2020      0       0    BB      America
1099   20/04/2020   20      4  2020      0       2    BY       Europe
1203   20/04/2020   20      4  2020   1313     230    BE       Europe
1315   20/04/2020   20      4  2020      0       0    BZ      America
1343   20/04/2020   20      4  2020      0       0    BJ       Africa
1378   20/04/2020   20      4  2020      0       0    BM      America
1410   20/04/2020   20      4  2020      0       0    BT         Asia
1448   20/04/2020   20      4  2020     44       1    BO      America
1487   20/04/2020   20      4  2020      1       0    BQ      America
1506   20/04/2020   20      4  2020     15       1    BA       Europe
1545   20/04/2020   20      4  2020      5       0    BW       Africa
1565   20/04/2020   20      4  2020   2055     115    BR      America
1677   20/04/2020   20      4  2020      1       1    VG      America
1702   20/04/2020   20      4  2020      1       0    BN         Asia
...           ...  ...    ...   ...    ...     ...   ...          ...
10245  20/04/2020   20      4  2020      0       0    SS       Africa
10260  20/04/2020   20      4  2020   4218     410    ES       Europe
10372  20/04/2020   20      4  2020     41       0    LK         Asia
10475  20/04/2020   20      4  2020      0       0    SD       Africa
10513  20/04/2020   20      4  2020      0       0    SR      America
10545  20/04/2020   20      4  2020    563      29    SE       Europe
10657  20/04/2020   20      4  2020    336      24    CH       Europe
10769  20/04/2020   20      4  2020      1       1    SY         Asia
10798  20/04/2020   20      4  2020     22       0    TW         Asia
10908  20/04/2020   20      4  2020     32       0    TH         Asia
11013  20/04/2020   20      4  2020      1       0    TL         Asia
11043  20/04/2020   20      4  2020      0       0    TG       Africa
11081  20/04/2020   20      4  2020      0       0    TT      America
11120  20/04/2020   20      4  2020     13       1    TN       Africa
11163  20/04/2020   20      4  2020   3977     127    TR         Asia
11201  20/04/2020   20      4  2020      0       0    TC      America
11228  20/04/2020   20      4  2020      0       0    UG       Africa
11258  20/04/2020   20      4  2020    261      10    UA       Europe
11296  20/04/2020   20      4  2020    479       4    AE         Asia
11402  20/04/2020   20      4  2020   5850     596    UK       Europe
11514  20/04/2020   20      4  2020     22       0    TZ       Africa
11549  20/04/2020   20      4  2020  24601    1772    US      America
11661  20/04/2020   20      4  2020      0       0    VI      America
11688  20/04/2020   20      4  2020      4       1    UY      America
11725  20/04/2020   20      4  2020     70       0    UZ         Asia
11761  20/04/2020   20      4  2020     29       0    VE      America
11798  20/04/2020   20      4  2020      0       0    VN         Asia
11906  20/04/2020   20      4  2020      0       0    YE         Asia
11917  20/04/2020   20      4  2020      4       1    ZM       Africa
11950  20/04/2020   20      4  2020      0       0    ZW       Africa

      countryterritoryCode  popData2018            countriesAndTerritories
0                      AFG   37172386.0                        Afghanistan
102                    ALB    2866376.0                            Albania
145                    DZA   42228429.0                            Algeria
252                    AND      77006.0                            Andorra
290                    AGO   30809762.0                             Angola
320                    NaN          NaN                           Anguilla
345                    ATG      96286.0                Antigua_and_Barbuda
377                    ARG   44494502.0                          Argentina
422                    ARM    2951776.0                            Armenia
525                    ABW     105845.0                              Aruba
554                    AUS   24992369.0                          Australia
666                    AUT    8847037.0                            Austria
778                    AZE    9942334.0                         Azerbaijan
883                    BHS     385640.0                            Bahamas
917                    BHR    1569439.0                            Bahrain
1028                   BGD  161356039.0                         Bangladesh
1065                   BRB     286641.0                           Barbados
1099                   BLR    9485386.0                            Belarus
1203                   BEL   11422068.0                            Belgium
1315                   BLZ     383071.0                             Belize
1343                   BEN   11485048.0                              Benin
1378                   BMU      63968.0                            Bermuda
1410                   BTN     754394.0                             Bhutan
1448                   BOL   11353142.0                            Bolivia
1487                   NaN          NaN  Bonaire, Saint Eustatius and Saba
1506                   BIH    3323929.0             Bosnia_and_Herzegovina
1545                   BWA    2254126.0                           Botswana
1565                   BRA  209469333.0                             Brazil
1677                   VGB      29802.0             British_Virgin_Islands
1702                   BRN     428962.0                  Brunei_Darussalam
...                    ...          ...                                ...
10245                  SSD   10975920.0                        South_Sudan
10260                  ESP   46723749.0                              Spain
10372                  LKA   21670000.0                          Sri_Lanka
10475                  SDN   41801533.0                              Sudan
10513                  SUR     575991.0                           Suriname
10545                  SWE   10183175.0                             Sweden
10657                  CHE    8516543.0                        Switzerland
10769                  SYR   16906283.0                              Syria
10798                  TWN   23780452.0                             Taiwan
10908                  THA   69428524.0                           Thailand
11013                  TLS    1267972.0                        Timor_Leste
11043                  TGO    7889094.0                               Togo
11081                  TTO    1389858.0                Trinidad_and_Tobago
11120                  TUN   11565204.0                            Tunisia
11163                  TUR   82319724.0                             Turkey
11201                  TCA      31458.0           Turks_and_Caicos_islands
11228                  UGA   42723139.0                             Uganda
11258                  UKR   44622516.0                            Ukraine
11296                  ARE    9630959.0               United_Arab_Emirates
11402                  GBR   66488991.0                     United_Kingdom
11514                  TZA   56318348.0        United_Republic_of_Tanzania
11549                  USA  327167434.0           United_States_of_America
11661                  VIR     106977.0       United_States_Virgin_Islands
11688                  URY    3449299.0                            Uruguay
11725                  UZB   32955400.0                         Uzbekistan
11761                  VEN   28870195.0                          Venezuela
11798                  VNM   95540395.0                            Vietnam
11906                  YEM   28498687.0                              Yemen
11917                  ZMB   17351822.0                             Zambia
11950                  ZWE   14439018.0                           Zimbabwe

[205 rows x 11 columns]

In [18]:
today_data.to_json('./probando.json',orient='records')